import { Card } from '../components'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <>
      <Head>
        <title>Social Media Links</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.containerLogo}>
          <Image src='https://img.icons8.com/office/100/000000/logo.png'
            alt="logo"
            width={64}
            height={64}
          />
          <div>
            <p>Your logo</p>
          </div>
        </div>
        <Card
          src='https://img.icons8.com/bubbles/100/000000/whatsapp.png'
          description='Whatsapp'
        />
        <Card
          src='https://img.icons8.com/bubbles/100/000000/instagram-new--v2.png'
          description='Instagram'
        />
        <Card
          src='https://img.icons8.com/bubbles/100/000000/facebook-new.png'
          description='Facebook'
        />
        <Card
          src='https://img.icons8.com/office/100/000000/twitter.png'
          description='Twitter'
          imgSize={40}
        />
        <Card
          src='https://img.icons8.com/dusk/100/000000/github.png'
          description='GitHub'
          imgSize={40}
        />
        <Card
          src='https://img.icons8.com/bubbles/100/000000/tiktok.png'
          description='TikTok'
        />
      </main>
    </>
  )
}

export default Home
// <img src="https://img.icons8.com/bubbles/100/000000/tiktok.png"/>